name: python3 setup.py lint

# Run lint CI on changes to main branch, or any PR to main. Do not run CI on
# any other branch.
# run only if there are changes on files that are linted (C, python and rst files)
on:
  push:
    branches: main
    paths:
      - '**.h'
      - '**.c'
      - '**.py'
      - '**.rst'

  pull_request:
    branches:
      - main
      - 'v**'
    paths:
      - '**.h'
      - '**.c'
      - '**.py'
      - '**.rst'

jobs:
  format-lint-code-check:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.0.2

      # This job will be completly be replaced by the pre-commit job in #4200

